### ISSUE TITLE
Requirement on the number of clients

### ISSUE THREAD

**Issue by pierreeliseeflory** [MohamadMansouri/fault-tolerant-secure-agg#1]
Hi,

For small number of clients (<33), the benchmark for the novel protocol (`benchmark_ours.py`) shows some weird behavior: some configurations produce partially incorrect results (masked_aggregation != clear_aggregation for some subset of the results) with errors being mostly off by one (eg for inputsize 16 : 95488 != 95489) but also sometimes producing completely incorrect results (912949 != 1220918).

For the following configuration:

```python
- dimension = 100
- dropout = 0.0
- threshold = 2/3
- inputsize = 16
```
The following numbers of clients produce such errors while the other produce correct results:

```bash
2,3,4,6,7,8,13,14,15,16,27,28,29,30,31,32
```

Below is an example of the values produced for such a failing configuration. Notice the errors are only off by one and intermittent up until the index 48, from which all values are incorrect with non trivial differences. 

```bash
Run number 1/1 (0/0 succesfull): dimension = 100, nclients = 32, dropout = 0.0
n°1: 1076201 != 1076202
n°3: 991664 != 991665
n°6: 1000743 != 1000744
n°7: 918930 != 918931
n°12: 1231458 != 1231459
n°13: 1093930 != 1093931
n°17: 970056 != 970057
n°18: 1043896 != 1043897
n°20: 821038 != 821039
n°22: 1044250 != 1044251
n°23: 1201942 != 1201943
n°24: 1123544 != 1123545
n°26: 1054126 != 1054127
n°27: 1001437 != 1001438
n°30: 1211859 != 1211860
n°31: 960535 != 960536
n°33: 983275 != 983276
n°34: 878949 != 878950
n°42: 1047000 != 1047001
n°43: 1046310 != 1046311
n°45: 995166 != 995167
n°47: 1217282 != 1217283
n°48: 1307565 != 1087171
n°49: 1041783 != 1204379
n°50: 1093142 != 1157742
n°51: 1193591 != 782926
n°52: 1018778 != 1442771
n°53: 1278416 != 998476
n°54: 940704 != 1282515
n°55: 1130042 != 1110295
n°56: 1254098 != 1144596
n°57: 882711 != 1023178
n°58: 937544 != 941863
n°59: 1030241 != 915413
n°60: 902720 != 962556
n°61: 1000444 != 956976
n°62: 986819 != 1029295
n°63: 1246479 != 970072
n°64: 1029936 != 1198309
n°65: 1139729 != 1080444
n°66: 1086558 != 909074
n°67: 1147510 != 1353983
n°68: 1068711 != 1030271
n°69: 858062 != 1127018
n°70: 1293865 != 1050529
n°71: 1130031 != 1091628
n°72: 1117494 != 1158570
n°73: 1114582 != 1091247
n°74: 1061677 != 1123034
n°75: 890639 != 1122180
n°76: 1065484 != 973287
n°77: 982927 != 878864
n°78: 1015154 != 1150563
n°79: 990505 != 991240
n°80: 1062117 != 964503
n°81: 946129 != 1002896
n°82: 974202 != 1154455
n°83: 1168342 != 794838
n°84: 1318124 != 1127316
n°85: 948539 != 1213334
n°86: 967535 != 1097861
n°87: 912523 != 968824
n°88: 1152270 != 985991
n°89: 1322466 != 1085647
n°90: 1024124 != 1498987
n°91: 888453 != 787541
n°92: 1151972 != 1046668
n°93: 1067242 != 936172
n°94: 1295216 != 1277066
n°95: 984557 != 1266160
n°96: 1014314 != 1036714
n°97: 965111 != 830103
n°98: 1013174 != 957667
n°99: 1265982 != 981288
Finished. Successful tests: 0/1
```

This behavior seem not to appear for configurations with large number of clients, so is there a requirement on the number of clients or is it unrelated ?

**Comment by MohamadMansouri** [comment]
Hi @pierreeliseeflory,
Thanks for opening this issue. 
Indeed this bug was previously pointed out by a colleague. I fixed it but it seems that I forgot to push the fix to github. 
I will push it by the end of the next week as I do not have access to my workspace now. 

Best, 
Mohamad

**Comment by MohamadMansouri** [comment]
Hi @pierreeliseeflory , 
Sorry for the delay. Actually, it was not the bug I thought it was. But anyway I found it and fixed it. 
Please let me know if you still see an issue. 

Best, 
Mohamad
